//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecolab.Pages.Config {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class PageClassSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static PageClassSettings defaultInstance = ((PageClassSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PageClassSettings())));
        
        public static PageClassSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20000")]
        public int MaxTimeoutValue {
            get {
                return ((int)(this["MaxTimeoutValue"]));
            }
            set {
                this["MaxTimeoutValue"] = value;
            }
        }
    }
}
