//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMC.DataAccess.SQL
{
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resource
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resource()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataAccess.SQL.Resource", typeof(Resource).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		protected internal static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to SELECT		FirstName
		///		,	LastName
		///		,	Email
		///		,	ZipCode
		///		,	CityName
		///		,	StateName
		///		,	Portal		
		///FROM		[InvalidBVT$]
		///WHERE		IsActive = &apos;Yes&apos;
		///
		///
		///.
		/// </summary>
		internal static string GetInvalidRIFData
		{
			get
			{
				return ResourceManager.GetString("GetInvalidRIFData", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to SELECT		FirstName
		///		,	LastName
		///		,	Email
		///		,	ZipCode
		///		,	RepCode
		///		,	Portal		
		///FROM		[SourceCodeBVT$]
		///WHERE		IsActive = &apos;Yes&apos;
		///
		///
		///.
		/// </summary>
		internal static string GetSourceCodeData
		{
			get
			{
				return ResourceManager.GetString("GetSourceCodeData", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to SELECT		FirstName
		///		,	LastName
		///		,	Email
		///		,	ZipCode
		///		,	Portal		
		///FROM		[StraightBVT$]
		///WHERE		IsActive = &apos;Yes&apos;
		///
		///
		///.
		/// </summary>
		internal static string GetStrightRIFData
		{
			get
			{
				return ResourceManager.GetString("GetStrightRIFData", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to SELECT		Name
		///		,	Data		
		///FROM		[TestParameter$]
		///WHERE	TestName = @TestName
		///.
		/// </summary>
		internal static string GetTestData
		{
			get
			{
				return ResourceManager.GetString("GetTestData", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to SELECT		NAME
		///		,	SALARY
		///FROM	sampletable
		///WHERE	Name = @Name.
		/// </summary>
		internal static string SampleSalaryValidator
		{
			get
			{
				return ResourceManager.GetString("SampleSalaryValidator", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to SELECT		Column1
		///		,	Column2
		///		,	Column3		
		///FROM		TrialTable2
		///.
		/// </summary>
		internal static string SampleValidator
		{
			get
			{
				return ResourceManager.GetString("SampleValidator", resourceCulture);
			}
		}
	}
}
